version: "3.8"

services:
  app:
    build: ./server
    restart: always
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
  frontend:
    depends_on:
      - app
    build: ./client
    restart: always
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
  # db:
  #   image: mongo:4.1.8-xenial
  #   container_name: db
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:
  #     - mongo:/data/db
  #   ports:
  #     - $MONGO_PORT:27017
  #   restart: unless-stopped
